
bridges = []

[[instances]]
name = "mutual-credit"
id = "mutual-credit-template"
dna_hash = "QmbMLgCrZBKqaxM3ygmGa73GuSGx9ptQted2sFdLHDcKmc"
uri = "file:./dnas/community-currency/dist/community-currency.dna.json"

[[instances]]
name = "lobby"
id = "lobby"
dna_hash = "QmYF9JC7hbBqyThch4jRooXrXgh9EkgbDnTTQeRZ8mVvxQ"
uri = "file:./dnas/lobby/dist/lobby.dna.json"

[[UIs]]
name = "Community Currency"
uri = "file:./ui/dist/ui.zip"

[[UIs.instance_references]]
ui_handle = "lobby-instance"
instance_id = "lobby"
