
bridges = []

[[instances]]
name = "mutual-credit-template"
id = "mutual-credit-template"
dna_hash = "QmbMLgCrZBKqaxM3ygmGa73GuSGx9ptQted2sFdLHDcKmc"
uri = "https://github.com/holochain-open-dev/community-mutual-credit/releases/download/test-0/community-currency.dna.json"

[[instances]]
name = "lobby-instance"
id = "lobby-instance"
dna_hash = "QmYF9JC7hbBqyThch4jRooXrXgh9EkgbDnTTQeRZ8mVvxQ"
uri = "https://github.com/holochain-open-dev/community-mutual-credit/releases/download/test-0/lobby.dna.json"

[[UIs]]
name = "Community Currency"
uri = "https://github.com/holochain-open-dev/community-mutual-credit/releases/download/test-0/ui.zip"

[[UIs.instance_references]]
ui_handle = "lobby-instance"
instance_id = "lobby-instance"
