
bridges = []

[[instances]]
name = "mutual-credit-template"
id = "mutual-credit-template"
dna_hash = "QmXAfJ2kWkP191V3CRmonKpJRpqHvUVGa7CbL4F8jiojTy"
uri = "https://github.com/holochain-open-dev/community-mutual-credit/releases/download/test-0/community-currency.dna.json"

[[instances]]
name = "lobby-instance"
id = "lobby-instance"
dna_hash = "QmQFbugQYw8XAWCmfKAEDTXJ9MkbxEqKrA3J4wrotbgjJy"
uri = "https://github.com/holochain-open-dev/community-mutual-credit/releases/download/test-0/lobby.dna.json"

[[UIs]]
name = "Community Mutual-Credit"
uri = "https://github.com/holochain-open-dev/community-mutual-credit/releases/download/test-0/ui.zip"

[[UIs.instance_references]]
ui_handle = "lobby-instance"
instance_id = "lobby-instance"
