persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'alice-agent'
name = 'alice'
public_address = 'HcSCipJrCpZzn5ga45eP9K3qhxHJiabtszGX6nsOkfkdtgeaVc7ydBeIXagn7pr'
keystore_file = './alice.key'

[[dnas]]
file = '../../dnas/lobby/dist/lobby.dna.json'
hash = 'QmYF9JC7hbBqyThch4jRooXrXgh9EkgbDnTTQeRZ8mVvxQ'
id = 'lobby-dna'

[[dnas]]
file = '../../dnas/community-currency/dist/community-currency.dna.json'
hash = 'QmbMLgCrZBKqaxM3ygmGa73GuSGx9ptQted2sFdLHDcKmc'
id = 'mutual-credit-template'

[[instances]]
agent = 'alice-agent'
dna = 'lobby-dna'
id = 'lobby-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'lobby-instance'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false

[network]
type = "sim2h"
sim2h_url = "ws://localhost:9000"
