bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'carol-agent'
name = 'carol'
public_address = 'HcScJ6a643WY4kKJohi3Jfc354QZxIdnkzvm4fQ9R8NicuksH849MbVyhgennvi'
keystore_file = './5.key'

[[dnas]]
file = './lobby/dist/lobby.dna.json'
hash = 'QmSagrCgkco3Y4dSoPECBXK7SUAhuboWufuwAxHukPWYDa'
id = 'lobby-dna'

[[dnas]]
file = './community-currency/dist/community-currency.dna.json'
hash = 'QmSCjUCaqVd9M5fAK3zXnqf2VDiqpEtkiwuaWvu9DWmbAs'
id = 'mutual-credit-dna'

[[instances]]
agent = 'carol-agent'
dna = 'lobby-dna'
id = 'lobby-instance'

[instances.storage]
type = 'memory'

[[instances]]
agent = 'carol-agent'
dna = 'mutual-credit-dna'
id = 'mutual-credit-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'lobby-instance'

[[interfaces.instances]]
id = 'mutual-credit-instance'

[interfaces.driver]
port = 8892
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false

[network]
type = "sim2h"
sim2h_url = "ws://localhost:9000"