bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'dave-agent'
name = 'dave'
public_address = 'HcScigUzSbX9ebpo73yr8TqiWN9Cfwkvx65NCZO7tS7GNtr8Rf3YyY6XxPtyvia'
keystore_file = './dave.key'

[[dnas]]
file = '../../dnas/lobby/dist/lobby.dna.json'
hash = 'QmQFbugQYw8XAWCmfKAEDTXJ9MkbxEqKrA3J4wrotbgjJy'
id = 'lobby-dna'

[[dnas]]
file = '../../dnas/community-currency/dist/community-currency.dna.json'
hash = 'QmXAfJ2kWkP191V3CRmonKpJRpqHvUVGa7CbL4F8jiojTy'
id = 'mutual-credit-template'

[[instances]]
agent = 'dave-agent'
dna = 'lobby-dna'
id = 'lobby-instance'

[instances.storage]
path = 'storage/lobby-instance'
type = 'lmdb'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'lobby-instance'

[interfaces.driver]
port = 8891
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false

[network]
type = "sim2h"
sim2h_url = 'ws://public-v4.sim2h.net:9000'
