bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'port-agent'
name = 'port'
public_address = 'HcScI7RDXHw38Seyv4suZM77Whrtdex7vn4E4hFOSz53M63tM5Nc9Qf3mxFnvea'
keystore_file = './port.key'

[[dnas]]
file = '../../dnas/lobby/dist/lobby.dna.json'
hash = 'QmYF9JC7hbBqyThch4jRooXrXgh9EkgbDnTTQeRZ8mVvxQ'
id = 'lobby-dna'

[[dnas]]
file = './community-currency.dna.json'
hash = 'QmfDzJRnkrnZx6Cd7UsKszS7xPMxshuYCaMfqNMcchppvt'
id = 'mutual-credit-dna'

[[instances]]
agent = 'port-agent'
dna = 'lobby-dna'
id = 'lobby-instance'

[instances.storage]
path = 'storage/lobby-instance'
type = 'lmdb'

[[instances]]
agent = 'port-agent'
dna = 'mutual-credit-dna'
id = 'mutual-credit-instance'

[instances.storage]
path = 'storage/mutual-credit-instance'
type = 'lmdb'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'lobby-instance'

[[interfaces.instances]]
id = 'mutual-credit-instance'

[interfaces.driver]
port = 8890
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false

[network]
type = "sim2h"
sim2h_url = 'ws://localhost:9000'
