bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'bob-agent'
name = 'bob'
public_address = 'HcSCjvyaY5Mkzazdcx655IY6X54uMmVRsfK8x4mms8FT8n7gsEGqzpf3I4xc6ci'
keystore_file = './bob.key'

[[dnas]]
file = '../../dnas/lobby/dist/lobby.dna.json'
hash = 'QmYF9JC7hbBqyThch4jRooXrXgh9EkgbDnTTQeRZ8mVvxQ'
id = 'lobby-dna'

[[dnas]]
file = '../../dnas/community-currency/dist/community-currency.dna.json'
hash = 'QmXAfJ2kWkP191V3CRmonKpJRpqHvUVGa7CbL4F8jiojTy'
id = 'mutual-credit-template'

[[instances]]
agent = 'bob-agent'
dna = 'lobby-dna'
id = 'lobby-instance'

[instances.storage]
path = 'storage/lobby-instance'
type = 'lmdb'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'lobby-instance'

[interfaces.driver]
port = 8889
type = 'websocket'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false

[network]
type = "sim2h"
sim2h_url = 'ws://public-v4.sim2h.net:9000'
